### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by XCHSystems** [davedude1011/sparx-helper#2]
Many thanks for the script, we have been looking for something for the bookmark checks as my son has ADHD and the bookmark checks are an unneccesary distraction.  However we cannot get the script to work, we have followed the windows instructions, but the bookwork checks come up and do not automatically populate and just sit there.

**Comment by davedude1011** [comment]
Without more info its hard to give a solution, but ive made an updated version if you're still interested, it uses a different method so should work more effectively.
https://github.com/davedude1011/Homework-Helper

**Comment by davedude1011** [comment]
> Many thanks for the script, we have been looking for something for the bookmark checks as my son has ADHD and the bookmark checks are an unneccesary distraction. However we cannot get the script to work, we have followed the windows instructions, but the bookwork checks come up and do not automatically populate and just sit there.

Without more info its hard to give a solution, but ive made an updated version if you're still interested, it uses a different method so should work more effectively.
https://github.com/davedude1011/Homework-Helper
